### PR TITLE
fix: stale style monkey patch in ComposeView

### LINKED ISSUE #835: Custom inboxSdk styles negatively impact composeView buttons
Screenshot 2023-02-02 at 12 07 41

The customStyles add more margin to the buttons and make the buttons overflow the composeView.
This is reproducible in gmail with the helloWorld app in this repo (and my custom chrome extensions) `"@inboxsdk/core": "0.2.27",`.

Would you accept a merge request with a config param to opt out of loading the styles?

### LINKED ISSUE #931: Loading InboxSDK causes issues with compose view Icon-set.
**Describe the bug**
Loading InboxSDK breaks the iconl-list for compose window.

**To Reproduce**

1. Please download/clone the [hello-world-inboxsdk](https://github.com/InboxSDK/hello-world) project. 
2. Once cloned, please comment all codes within the InboxSDK.load() call. (lines 4-15)
3. Build the updated code and sideload it to your Chrome browser.
4. Enable the Hello-World extension for Incognito browser.
5. Open an incognito window of Chrome.
6. Resize the Incognito Chrome's width to approximately half of the screen. (DO NOT USE THE FULL WIDTH OF SCREEN)
7. Open GMAIL in one of the tabs of the incognito-chrome.
8. Click on compose and wait for the compose window to popup.

**Expected behavior**
Compose windows shows and the icons are correctly shown a the bottom. Please see this uploaded image : 
https://imgur.com/a/U58aCur

**Screenshots**
With the inboxsdk library loaded, and the incognito-Chrome window is of the right size, the bottom icons will look a bit weird. Please see this image :  https://imgur.com/kwcxs5p

Notice that the delete/trash icon is now beyond the compose window and is already at the right hand bar for addons. 

**Add any other context about the problem here if anything**
Just some emphasis on the bug happening in incognito and when incognito-window is not in full screen.

Thanks

### PR DESCRIPTION
**Pull request by wegry**
Removes additional button padding and margin around the ComposeView toolbar. @hwfwalton pointed out these styles were added a number of major Gmail changes ago.

The `.inboxsdk__compose_narrow_buttons` class made compose toolbar buttons wider. This was happening irrespective of how wide the compose view was when it was created.

There is still the bug around composes and button overflow when the client is <= 1000px wide. I believe that should be fixed with Gmail handles narrower than 1000px screens with ComposeView. For clients wider than 1000px, this patch should allow native button styles through.

# Screenshots

At roughly 1000px wide with the [example extension found here.](https://github.com/InboxSDK/InboxSDK/blob/e957bfff657e0f7fe2fd3a2b9764738a6e1fd5cd/examples/compose-tooltip-button/content.js#L1)

## Before

Note the additional 15px of spacing between ComposeView toolbar buttons

Screenshot 2023-07-25 at 13 47 35

## After

Note that the _Delete_ draft button is overflowing the compose window here.

Screenshot 2023-07-25 at 13 42 00

Resolves #835, resolves #931

### CODE REVIEW

**Review by hwfwalton — APPROVED** [review]
The compose window DOM has changed significantly since these changes were first implemented and I the fact that our `inboxsdk__compose_narrow_buttons` now results in the buttons becoming **wider** is testament to the code rot.
As ever, I'd defer to @Macil, but these changes lgtm 👍

**Comment by Macil** [comment]
Can you check that this change doesn't hurt the styling of buttons in inline compose views?

**Review by Macil — APPROVED** [review]

**Comment by wegry** [comment]
We'll merge this and do a remote deploy around 12:00 UTC tomorrow. If things are quiet, we'll cut a `@inboxsdk/core@1.2.2` Monday.

**Comment by wegry** [comment]
@Macil for 

> Can you check that this change doesn't hurt the styling of buttons in inline compose views?

Custom toolbar buttons don't seem to be grouped in inline composes. Our stale monkey patch didn't seem to apply to inline composes either.

Screenshot 2023-07-26 at 15 45 22

**Pull request merged**
